### ISSUE TITLE
Beckhoff.TwinCAT.Ads.SymbolicServer reference

### ISSUE THREAD

**Issue by drvic10k** [Beckhoff/TF6000_ADS_DOTNET_V5_Samples#12]
The samples reference Beckhoff.TwinCAT.Ads.SymbolicServer 6.0.72, but that is not available as a NuGet package, instead the references to correct 6.0.74 version should be used

**Comment by RalfHeitmann** [comment]
I fixed that with the latest commit. Thx for reporting.
