### ISSUE TITLE
AdsSymbolicServer sample returning default values

### ISSUE THREAD

**Issue by drvic10k** [Beckhoff/TF6000_ADS_DOTNET_V5_Samples#14]
For the strings, the response is always empty string
For structs, the response is the struct with default values for all properties
Bool is false, integer is zero

etc.

![image](https://user-images.githubusercontent.com/3754571/161563238-aa3cff2f-b83a-4460-b4d4-19814f434e6b.png)

**Comment by RalfHeitmann** [comment]
Thxs,
I can confirm the issue. It will be fixed in the next version of the SymbolicServer package.

**Comment by drvic10k** [comment]
cool, when can we expect the next version?

**Comment by mark-lazarides** [comment]
> Its now available ;-)

So quick, @RalfHeitmann  :-)
