### ISSUE TITLE
Read values with .net

### ISSUE THREAD

**Issue by drvic10k** [Beckhoff/TF6000_ADS_DOTNET_V5_Samples#16]
Is there an example for reading the values from symbolic server using .net?

So far I can read the values using the powershell extension, but from .net I get an error

I receive the symbol information correctly:
![image](https://user-images.githubusercontent.com/3754571/162205853-8cebaa72-85aa-443a-bfa2-3309c112b9cd.png)

But when trying to get the value, I get an `DeviceSymbolNotFound` result
![image](https://user-images.githubusercontent.com/3754571/162206158-06bb0166-e9ff-4c6f-907c-15a54c086a9d.png)

Alternatively, when using
`Connection.ReadAsync(symbol.IndexGroup, symbol.IndexOffset, memory, cancel)`

I receive `Ads-Error 0x701 : Service is not supported by server.`

**Comment by RalfHeitmann** [comment]
The reason was, that the value access by InstancePath and the access by IG/IO wasn't fully supported. I fixed that with the commit above and added some demonstration code in the sample.
