### ISSUE TITLE
symbolFactory.ClearTypes() does not clear the types

### ISSUE THREAD

**Issue by drvic10k** [Beckhoff/TF6000_ADS_DOTNET_V5_Samples#26]
as far as I understood from debugging the code, the problem seems to be in `NamespaceCollection<T>`
There you have `private Dictionary<string, T> allTypes = new Dictionary<string, T>((IEqualityComparer<string>) StringComparer.OrdinalIgnoreCase);`

and in `NamespaceCollection` you add to `InnerAllTypes`, which points to this private field

but `symbolFactory.ClearTypes()` calls `ICollection<INamespace<IDataType>>.Clear()` and leaves this private field in the original state, so although the interfaces are cleared, the types are not

**Comment by RalfHeitmann** [comment]
Good point.
This will be fixed in Beckhoff.TwinCAT.Ads > 6.0.178 (future release)
