### ISSUE TITLE
Connection.WriteAsync not working

### ISSUE THREAD

**Issue by drvic10k** [Beckhoff/TF6000_ADS_DOTNET_V5_Samples#30]
with the `AdsSymbolicServer`, I cannot use `Connection.WriteAsync`, I had to replace the call with `Connection.WriteValueAsync`

is there some other method I need to override to make `WriteAsync` work? I am overriding
`protected override AdsErrorCode OnWriteRawValue(ISymbol symbol, ReadOnlySpan<byte> span)`

**Comment by RalfHeitmann** [comment]
Please give more information which overload of WriteAsync you are using because there are several paramater sets. Another important information what type of instance you want to write and the addressing (PrimitiveType, ComplexType).
What is the system reaction? Is the call just ignored or do you get an Exception? Is OnWriteRawValue called in this situation?

**Comment by drvic10k** [comment]
I am using this method:
```
public async Task<ResultWrite> WriteAsync(
      uint indexGroup,
      uint indexOffset,
      ReadOnlyMemory<byte> writeBuffer,
      CancellationToken cancel)
```

when writing one symbol I get this exception, it's a boolean value:
`Parameter size is incorrect. (AdsErrorCode: 1797, 0x705)` but with `Connection.WriteValueAsync` it works

another boolean value works with both methods

**Comment by RalfHeitmann** [comment]
```csharp
The relevant implementation part in the SymbolServer base class could be this one here:

protected virtual Task<ResultReadBytes> OnReadIgIoAsync(AmsAddress sender, uint invokeId, uint indexGroup, uint indexOffset, int readLength, CancellationToken cancel)
        {
            AdsErrorCode errorCode = AdsErrorCode.DeviceServiceNotSupported;
            ReadOnlyMemory<byte> readData = ReadOnlyMemory<byte>.Empty;

            SymbolIterator iter = new SymbolIterator(this.symbols, true);
            IAdsSymbol? symbol = iter.Cast<IAdsSymbol>().FirstOrDefault(s => s.IndexGroup == indexGroup && s.IndexOffset == indexOffset);

            if (symbol != null)
            {
                if (readLength >= symbol.GetValueMarshalSize())
                {
                    byte[] data = new byte[symbol.GetValueMarshalSize()];

                    try
                    {
                        errorCode = OnReadRawValue(symbol, data.AsSpan());

                        if (errorCode.Succeeded())
                            readData = data.AsMemory();
                    }
                    catch (Exception ex)
                    {
                        Debug.WriteLine(ex.Message);
                        errorCode = AdsErrorCode.InternalError;
                    }
                }
                else
                {
                    errorCode = AdsErrorCode.DeviceInvalidSize;
                }
            }
            return Task.FromResult(new ResultReadBytes(errorCode,readData));
     }
```

Could it be that the IndexGroup, IndexOffset combination returns a symbol that is ambigous or doesn't return the boolean symbol you expect?

**Comment by drvic10k** [comment]
I tried to override the method and set a breakpoint there, it doesn't hit it before the exception is thrown

**Comment by RalfHeitmann** [comment]
> another boolean value works with both methods

I really don't know where this issue should come from. It must have to do with the Symbol/Value:
If I add the following code into the AdSymbolicServer program.cs file (behind registering all Notifications):

```csharp
 // Receiving notifications on all Symbols
                        SymbolIterator iter = new SymbolIterator(symbols,true);
                        IList<ISymbol> allSymbols = iter.ToList();
                        disposables = ReceiveNotifications(session,allSymbols);

                       // Add this part for WriteAsync usage
                        IAdsSymbol b1 = (IAdsSymbol)symbols["Main.bool1"];
                        IAdsSymbol b2 = (IAdsSymbol)symbols["Globals.bool1"];
                        byte[] bytes = new byte[1];

                        for (int i = 0; i < 10; i++)
                        {
                            await Task.Delay(TimeSpan.FromSeconds(1.0));
                            bytes[0] = (bytes[0] == (byte)1) ? (byte)0 : (byte)1;
                            await session.Connection.WriteAsync(b1.IndexGroup, b1.IndexOffset, bytes.AsMemory(), CancellationToken.None);
                            await session.Connection.WriteAsync(b2.IndexGroup, b2.IndexOffset, bytes.AsMemory(), CancellationToken.None);
                        }
```
I even get the Ads Notifications from the Value toggling properly.
Also I don't see the potential for an DeviceInvalidSize return code other than described above (picking up the wrong symbol or Incorrect designed Symbol from IndexGroup/IndexOfset, or MemorySpan.Length != 1. Relevant is here the ByteSize of the Symbol (should be 1 for an boolean), and that WriteAsync gets the correct buffer size (also 1-byte).

**Comment by RalfHeitmann** [comment]
> when writing one symbol I get this exception, it's a boolean value: `Parameter size is incorrect. (AdsErrorCode: 1797, 0x705)` but with `Connection.WriteValueAsync` it works
> 
> another boolean value works with both methods

Is the problem still reproducable on your side?

**Comment by drvic10k** [comment]
yes, it is reproducible, I will try do some more investigation today to see what is the difference between those two values

**Comment by drvic10k** [comment]
so delving deeper, I found out, that the result of the operation is DeviceInvalidSize

can this be cause by the way the subsymbols are mapped?

![image](https://user-images.githubusercontent.com/3754571/180217978-10cd38cd-e908-4942-adf0-699ef40623c2.png)

here you can see that the struct has the same offset as the field

and I am trying to write the value like this:
`Connection.WriteAsync(symbol.IndexGroup, symbol.IndexOffset, memory, cancel)`, offset is 4154, allocated memory is one byte (4154 dec = 103A hex)

when writing the next value (103B), it works fine

same problem happens when reading

**Comment by drvic10k** [comment]
I tried to follow the code execution of this method, because it can write the symbol correctly, to see the difference:
```
public async Task<ResultWrite> WriteValueAsync(
      ISymbol symbol,
      object val,
      CancellationToken cancel)
```

there is a strange thing happening, this symbol
![image](https://user-images.githubusercontent.com/3754571/180231296-bcac2828-4b9a-44a1-8ca7-734fa6cd9a58.png)
is transformed to this:
![image](https://user-images.githubusercontent.com/3754571/180231786-3c21cb8d-407e-4d2e-99a3-ccc625044911.png)

in this method:
```
public async Task<ResultWrite> WriteValueAsync(
      string name,
      object value,
      CancellationToken cancel)
```

and then with this different index group and offset it somehow correctly arrives in the simulator with the original group and offset

**Comment by RalfHeitmann** [comment]
That explains the problem. There is a side effect in the AdsClient-side cached ISymbols when you use the "ReadValueXXX" and "WriteValueXXX" overloads (Changing the IndexGroup to **IndexGroupSymbolAccess.ValueByHandle** and the Handle as IndexOffset.

**Comment by RalfHeitmann** [comment]
Please try out the 6.0.190 ...

**Comment by drvic10k** [comment]
now it works, thanks
