### ISSUE TITLE
SumSymbolWrite asks for IList<ISymbol> but casts to Symbol class causing exceptions

### ISSUE THREAD

**Issue by maxxie85** [Beckhoff/TF6000_ADS_DOTNET_V5_Samples#34]
The SumSymbolWrite commands requires a IList of ISymbols in it's constructor. However if this is not a Symbol class instance the command fails with an exception, appearing to violate the Liskov substitution principle.

**Comment by RalfHeitmann** [comment]
Please try out the Version 6.0.207. Should be better.

**Comment by maxxie85** [comment]
Yes it's working as expected. 

Thank you.
