### ISSUE TITLE
PollValue order.

### ISSUE THREAD

**Issue by Barteling** [Beckhoff/TF6000_ADS_DOTNET_V5_Samples#36]
If we use poll values at high rate and the PC which polls is under heavy load, we noticed the the events are not always fired at the pc in the order in which they were polled on the PLC. 

Is it possible to improve on this?

We noticed this because we poll a timestamp from the PLC, for now we use this to reorder the read data but it would be better if we can trust the incoming event order as well.

**Comment by RalfHeitmann** [comment]
I am not fully aware of this scenario here. The 'events' you are talking about are coming all from the same 'Poll' call? In that case they all should be serialized.
If they come from different 'Poll' calls they are executed in different async background threads which potentially could overtake each other (on the client side) - especially when the calling PC is under heavy load as you describe.
At first sight, I think the only way to ensure the order is to synchronize your application, that the next ADS request is only sent after the previous ADS response is processed.

**Comment by Barteling** [comment]
It happen when I use sumread pollvalues and processing the first value I have long proccessing time, longer than my poll values interval. 

I made some test runs and printed the output of the date time value which we also use read in the sum read command:
This was my initial problem:
![1](https://user-images.githubusercontent.com/33071638/198574164-f427212f-7e38-44a2-b16c-2d0e1da5deac.png)

I noticed handling the values in the first run took almost 1 seconds so i optimized my code (in the invoke methods), which did fix the order:

![afbeelding](https://user-images.githubusercontent.com/33071638/198574549-5bca4b6f-fd65-4a9c-bc62-a927b75125d7.png)




However I still think that ideally the results should come in in order, and if one takes first long, this one might be off, but not all consecutive values which seem to come in randomly. 
i can simulate this problem with this code:

![afbeelding](https://user-images.githubusercontent.com/33071638/198574799-97507720-984c-41bd-95e8-2d0681a586da.png)

High load on the first value, all values after that are in random order.

**Comment by RalfHeitmann** [comment]
Seems to be the case that we have to much parallel processing here internally in PollValues resulting in Race-conditions in the Polling handler calls.
In the just released version 6.0.216
https://www.nuget.org/packages/Beckhoff.TwinCAT.Ads.Reactive/6.0.216
the handlers will be serialized. The Poll Trigger will still be called asynchonously (meaning that the Ads Request are going out on trigger also if the handler is blocked), but the Polling handler receives the new Data serialized without mixing up the order.
Hope that helps.

**Comment by RalfHeitmann** [comment]
Should be fixed with 6.0.216 and higher ...
