### ISSUE TITLE
Please make all .NET libraries Open Source

### ISSUE THREAD

**Issue by beppemarazzi** [Beckhoff/TF6000_ADS_DOTNET_V5_Samples#40]
Working with your libraries for integrate Ads with .NET services and applications, I found many minor issues.

I spent a lot of time with decompilers (ILSpy, dnSpy, ...) to understand the origin of the issues and work-around them....

In one case (#39) i was also able to use dnSpy to **modify the binary IL code into TwinCAT.Ads.SymbolicServer.dll** to fix it (correcting the wrong calls to `OnWriteRawValue` with the correct ones to `OnReadRawValue` while waiting for an official solution for the issue...)

Please consider to make Twincat.Ads.* libraries open source and share it on github. This may help a lot developers to understand how to actually use them since **they are a very good job** but somewhere the documentation is lacking or out-dated.

IMHO you may receive also al lot of PR helping you and your users to improve the product and by consequence all TwinCAT eco system...

**Comment by MichaelKno** [comment]
We will not make the TwinCAT.Ads libraries open source. 

We have another ADS component, which is open source: https://github.com/Beckhoff/ADS
