### ISSUE TITLE
Wrong complex struct marshalling

### ISSUE THREAD

**Issue by drvic10k** [Beckhoff/TF6000_ADS_DOTNET_V5_Samples#45]
I have the following structure:

```    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi, Pack = 1)]
    public struct SetupAds
    {
        public SetupAds()
        {
        }

        public string MqttIpAddress { get; init; } = "";

        public short LogLevel { get; init; } = 0;

        public string ApiVersion { get; init; } = "";
    }
```

![image](https://user-images.githubusercontent.com/3754571/214502686-aaad4c7a-584e-4ab2-8bc5-ce5e22349e34.png)

When I retrieve individual fileds, I get correct values back:

![image](https://user-images.githubusercontent.com/3754571/214508188-97ecbad4-4a18-4b8b-88e0-935e635a4f08.png)

But retrieving the whole structure is not correct and the string is different every time:

![image](https://user-images.githubusercontent.com/3754571/214508494-05744d0c-1e51-400c-9a69-fda171ca1c5c.png)

**Comment by RalfHeitmann** [comment]
Sorry, I'm a little bit of context here. You are implementing you own AdsSymbolicServer here? Or what is the situation?

On first sight, hte SetupAds structure is missing the Memory Layout here (and therefore would use Default Marshalling, which doesn't work with dynamic length strings!).

Have you tried to add the StructLayout attribute on your class/struct like this?

```csharp
[StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi, Pack = 1)]
struct SetupAds
{
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 81)]
        public string MqttIpAddress { get; init; } = "";
        [MarshalAs(UnmanagedType.I2)]
        public short LogLevel { get; init; } = 0;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 81)]
        public string ApiVersion { get; init; } = "";
}
```

You can check the correct marshalling size of your SetupAds struct with

```csharp
int sz = System.Runtime.InteropServices.Marshal.SizeOf(typeOf(SetupAds));
```
which should be 164.

**Comment by drvic10k** [comment]
> SetupAds structure is missing the Memory Layout here (and therefore would use Default Marshalling, which doesn't work with dynamic length strings!).

I was not aware of this, I will give it a try
thanks

**Comment by drvic10k** [comment]
it works with the additional attributes, thanks
