### ISSUE TITLE
AmsTcpIpRouter stops listening for connections after connect / disconnect

### ISSUE THREAD

**Issue by vvoldsund** [Beckhoff/TF6000_ADS_DOTNET_V5_Samples#47]
### Setup:
- One machine with .Net application running AmsTcpIpRouter and two intances of AdsServer
- Another machine with XAR running a native TwinCAT application that sets up one client for each the two servers and spamming it with packages.

### Configuration:
``` 
 "AmsRouter": {
    "Name": "MyLocalSystem",
    "NetId": "10.80.111.228.1.1",
    "TcpPort": 48898, // Default port from TwinCAT system is 48898
    "RemoteConnections": [
      {
        "Name": "CONTROLLER",
        "Address": "10.80.111.254",
        "NetId": "10.80.111.254.1.1",
        "Type": "TCP_IP"
      }
    ]
  },
```
### What happens:
As the application starts it start to listen for incomming connections on all network interfaces:
![image](https://user-images.githubusercontent.com/123375581/218058121-214920f3-cfa9-494b-908d-72f927d4a6c2.png)

After the clients connect it stops to listen for incomming connections (the servers receive data):
![image](https://user-images.githubusercontent.com/123375581/218057839-4a1c74de-e2bd-44dd-b33d-6b4273f89c6c.png)

If the application with the clients are restarted the connection is closed and does not recover (the servers does not receive data and the router does not listen for incoming connections):
![image](https://user-images.githubusercontent.com/123375581/218058560-c898c4da-8b63-4d0a-b32e-eb52b8e1fa72.png)

### Expected
Was expecting the router to keep listening for incoming connections after the first one connected and also after the disconnect. As it is now the AmsTcpIpRouter cannot be trusted as remote systems can be restarted randomly.

**Comment by RalfHeitmann** [comment]
Please check the newest versions of the 6.0.XXX and 6.1.XXX packages. The issue should be resolved.
