### ISSUE TITLE
Array of structs marshaled as null

### ISSUE THREAD

**Issue by drvic10k** [Beckhoff/TF6000_ADS_DOTNET_V5_Samples#48]
I have a problem with marshaling this type

```
[StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi, Pack = 1)]
public struct DataAds
{
    [MarshalAs(UnmanagedType.ByValArray, ArraySubType = UnmanagedType.Struct, SizeConst = 4)]
    public StructAds[] Structs;
}

[StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi, Pack = 1)]
public struct StructAds
{
    public int Field1;

    public int Field2;

    public int Field3;

    public int Field4;
}
```

when marshaling in AdsSymbolicServer like this:
`_symbolMarshaler.TryMarshal(symbol, value, span, out int _)`

I get the property Structs=null

Am I missing some attributes?

**Comment by RalfHeitmann** [comment]
The SymbolMarshaler doesn't need external classes to Marshal the symbol. The Symbol itself contains all information how to marshal the data. I have extended the AdsSymbolicServerSample with additional code that demonstrates accessing structs.
