### ISSUE TITLE
AdsClient crashes on malformed read responses

### ISSUE THREAD

**Issue by stegm** [Beckhoff/TF6000_ADS_DOTNET_V5_Samples#5]
We communicate via ADS to an EtherCAT Profibus-Master. For some reason the Master respond sometime with an malformed read response:

![grafik](https://user-images.githubusercontent.com/6886353/154494704-cef620d6-46db-46f5-8102-69b8d7ac6ed1.png)

The response set the Length to 240, but actually no data exists in the response.

This works fined in the old V4 version of the ADS client, but the new V5 (5.0.528) reports a ADS timeout and then stops working, until a new client is reconnected.

The log of the ADS client contains the following entry:

```
AmsServer failed with Error: Das angegebene Argument liegt ausserhalb des gültigen Wertebereichs.
Parametername: start  (Port 'AdsClient' (0))!
```

For me it seems that the client tries to access the non-existing data and the crashes somehow.

---

Raw-Data of the response:

![grafik](https://user-images.githubusercontent.com/6886353/154495853-ee55af59-4d7c-4ef1-9d84-b3472e857425.png)

**Comment by stegm** [comment]
The problem is that I cannot trigger on the `ArgumentOutOfRangeException` because it is inside the ADS-Dll. On the client side I get the following exception which is obviously not the root cause:

```
   at TwinCAT.Ads.AdsErrorCodeExtensions2.ThrowOnError(AdsErrorCode adsErrorCode)
   at TwinCAT.Ads.AdsClient.Read(UInt32 indexGroup, UInt32 indexOffset, Memory`1 readBuffer)
   at AdsResponseError.Program.Main(String[] args) in c:\temp\AdsResponseError\AdsResponseError\Program.cs:line 25
```

Unfortunately the mentioned log messages does not contain a stack trace either.

But I attached a simple program which uses the `AdsServer` class to produce such a malformed read response message.

[Program.zip](https://github.com/Beckhoff/TF6000_ADS_DOTNET_V5_Samples/files/8096465/Program.zip)

This programm produces the following malformed response which crashes the client.

![grafik](https://user-images.githubusercontent.com/6886353/154668968-48a8181c-4f59-470e-afb3-b31034b14323.png)

**Comment by RalfHeitmann** [comment]
Thanks for reporting this. I could detect and fix the problem.
The behaviour of the 5.x will be a little bit different from the 4.x, it will throw an AdsErrorException with AdsErrorCode.ClientResponseInvalid immediatly with receiving the invalid frame.
I assume the 4.x just ignores the erraneous frame and then throws an AdsErrorException with AdsErrorCode.ClientSyncTimout after timeout (what is valid, but suboptimal because the calling thread blocks until timeout).
Please have a look at the upcoming release(s).

**Comment by boj4n** [comment]
Crashes OnADSNotification first call. _binRead is null

![image](https://user-images.githubusercontent.com/13449663/156192378-6b1c8c3c-80e2-4927-b830-b3d29949d15a.png)
