### ISSUE TITLE
RouterStateChanged event not triggered from IPC

### ISSUE THREAD

**Issue by DonMiguelSan** [Beckhoff/TF6000_ADS_DOTNET_V5_Samples#50]
I have two scenarios, when I test the behavior using the local AMSNetID the event is triggered, as soon as i am connected to a remote host the event is not triggered, my connection to the remote host is using ADS not secure, this is happening with the following version from the nuget package: 6.0.273

**Comment by RalfHeitmann** [comment]
The RouterStateChanged event indicates that the state of the **local** Router has changed. There is actually no way to receive RouterStateChanged events from Remote Systems.
